import * as XLSX from 'xlsx'

import Attendance from '../models/Attendance.js'
import Student from '../models/Student.js'

async function buildMonthlySummary({ department, semester, shift, subject, month }) {
  const monthDate = new Date(month + '-01')
  if (isNaN(monthDate.getTime())) {
    const err = new Error('Invalid month format. Use YYYY-MM.')
    err.status = 400
    throw err
  }

  const year = monthDate.getFullYear()
  const monthIndex = monthDate.getMonth()
  
  const startDate = new Date(year, monthIndex, 1)
  const endDate = new Date(year, monthIndex + 1, 1)

  const students = await Student.find({ 
    department, 
    semester, 
    shift,
    status: 'active'
  }).sort({ pin: 1 }).lean()

  if (students.length === 0) {
    const err = new Error('No students found for selected class')
    err.status = 404
    throw err
  }

  const attendanceRecords = await Attendance.find({
    department,
    semester,
    shift,
    subject,
    date: { $gte: startDate, $lt: endDate }
  }).lean()

  const uniqueDates = [...new Set(attendanceRecords.map(r => 
    new Date(r.date).toISOString().slice(0, 10)
  ))].sort()
  
  const workingDays = uniqueDates.length

  const studentStats = new Map()
  
  students.forEach(student => {
    studentStats.set(student.pin, {
      pin: student.pin,
      name: student.name,
      totalPeriods: 0,
      presentPeriods: 0,
      absentPeriods: 0,
      dailyPeriods: new Map()
    })
  })

  attendanceRecords.forEach(record => {
    const dateStr = new Date(record.date).toISOString().slice(0, 10)
    const period = record.period
    
    record.absentees.forEach(pin => {
      const student = studentStats.get(pin)
      if (student) {
        if (!student.dailyPeriods.has(dateStr)) {
          student.dailyPeriods.set(dateStr, { present: 0, absent: 0 })
        }
        student.dailyPeriods.get(dateStr).absent++
        student.absentPeriods++
      }
    })

    record.presents.forEach(pin => {
      const student = studentStats.get(pin)
      if (student) {
        if (!student.dailyPeriods.has(dateStr)) {
          student.dailyPeriods.set(dateStr, { present: 0, absent: 0 })
        }
        student.dailyPeriods.get(dateStr).present++
        student.presentPeriods++
      }
    })
  })

  // Calculate total periods for each student
  studentStats.forEach(student => {
    student.dailyPeriods.forEach((periods, dateStr) => {
      student.totalPeriods += (periods.present + periods.absent)
    })
    
    student.percentage = student.totalPeriods > 0 ? (student.presentPeriods / student.totalPeriods) * 100 : 0
    delete student.dailyPeriods
  })

  const result = Array.from(studentStats.values()).map(student => ({
    pin: student.pin,
    name: student.name,
    totalPeriods: student.totalPeriods,
    presentPeriods: student.presentPeriods,
    absentPeriods: student.absentPeriods,
    percentage: Number(student.percentage.toFixed(2))
  }))

  return {
    subject,
    month,
    totalPeriods: result.length > 0 ? result[0].totalPeriods : 0,
    students: result
  }
}

export async function getMonthlySummary(req, res) {
  try {
    const { department, semester, shift, subject, month } = req.query || {}
    if (!department || !semester || !shift || !subject || !month) {
      return res
        .status(400)
        .json({ message: 'department, semester, shift, subject, month are required' })
    }

    const result = await buildMonthlySummary({ department, semester, shift, subject, month })
    return res.json(result)
  } catch (err) {
    const status = err.status || 500
    return res.status(status).json({ message: err.message || 'Failed to build monthly summary' })
  }
}

export async function exportMonthlyExcel(req, res) {
  try {
    const { department, semester, shift, subject, month } = req.query || {}
    if (!department || !semester || !shift || !subject || !month) {
      return res
        .status(400)
        .json({ message: 'department, semester, shift, subject, month are required' })
    }

    const data = await buildMonthlySummary({ department, semester, shift, subject, month })

    // Create workbook and worksheet
    const wb = XLSX.utils.book_new()
    const wsData = [
      ['PIN', 'Name', 'Total Periods', 'Periods Attended', 'Periods Missed', '%']
    ]
    
    // Add student data
    data.students.forEach(student => {
      wsData.push([
        student.pin,
        student.name,
        student.totalPeriods,
        student.presentPeriods,
        student.absentPeriods,
        `${student.percentage}%`
      ])
    })
    
    // Add summary information
    wsData.push([])
    wsData.push(['Total Periods:', data.totalPeriods])
    wsData.push(['Subject:', subject])
    wsData.push(['Month:', month])
    wsData.push(['Generated By:', 'Faculty Log Book System'])
    
    const ws = XLSX.utils.aoa_to_sheet(wsData)
    XLSX.utils.book_append_sheet(wb, ws, `${subject} - ${month}`)

    const filename = `${subject}_${month}_attendance_report.xlsx`
    const excelBuffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)

    res.send(excelBuffer)
  } catch (err) {
    const status = err.status || 500
    return res.status(status).json({ message: err.message || 'Failed to export report' })
  }
}

// Helper function to get weekly register data (shared between getWeeklyRegister and exportWeeklyExcel)
async function getWeeklyRegisterData({ department, semester, shift, weekStart }) {
  const startDate = new Date(weekStart)
  if (isNaN(startDate.getTime())) {
    throw new Error('Invalid weekStart format. Use YYYY-MM-DD.')
  }

  // Ensure weekStart is a Monday
  const dayOfWeek = startDate.getDay()
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek
  const monday = new Date(startDate)
  monday.setDate(startDate.getDate() + mondayOffset)
  
  const saturday = new Date(monday)
  saturday.setDate(monday.getDate() + 5)

  console.log('Week range:', { 
    weekStart: monday.toISOString().slice(0, 10), 
    weekEnd: saturday.toISOString().slice(0, 10) 
  })

  // Get all students for the class
  const students = await Student.find({ 
    department, 
    semester, 
    shift,
    status: 'active'
  }).sort({ pin: 1 }).lean()

  console.log('Found students:', students.length)

  if (students.length === 0) {
    throw new Error('No students found for selected class')
  }

  // Get attendance records for the week (all periods, all subjects)
  const attendanceRecords = await Attendance.find({
    department,
    semester,
    shift,
    date: { 
      $gte: monday, 
      $lte: saturday 
    }
  }).sort({ date: 1, period: 1 }).lean()

  console.log('Found attendance records:', attendanceRecords.length)
  if (attendanceRecords.length > 0) {
    console.log('Sample attendance record:', attendanceRecords[0])
  }

  // Transform data into register format
  const registerData = {}
  const weekDates = []

  // Initialize week dates
  for (let i = 0; i < 6; i++) {
    const currentDate = new Date(monday)
    currentDate.setDate(monday.getDate() + i)
    const dateStr = currentDate.toISOString().slice(0, 10)
    const formatted = `${currentDate.getDate().toString().padStart(2, '0')}/${(currentDate.getMonth() + 1).toString().padStart(2, '0')}/${currentDate.getFullYear()}`
    const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    const day = dayNames[currentDate.getDay()]
    
    weekDates.push({
      date: dateStr,
      formatted,
      day
    })
    
    registerData[dateStr] = {}
  }

  // Initialize all students as absent for all periods (default)
  students.forEach(student => {
    weekDates.forEach(weekDate => {
      registerData[weekDate.date][student.pin] = [false, false, false, false, false, false, false]
    })
  })

  // Fill in actual attendance data - process each record only once
  attendanceRecords.forEach(record => {
    const dateStr = new Date(record.date).toISOString().slice(0, 10)
    const period = record.period - 1 // Convert to 0-based index
    
    // Only process if this date is in our week range
    if (!registerData[dateStr]) return
    
    // Mark present students
    if (record.presents && Array.isArray(record.presents) && record.presents.length > 0) {
      record.presents.forEach(pin => {
        if (registerData[dateStr][pin] && registerData[dateStr][pin][period] !== undefined) {
          registerData[dateStr][pin][period] = true
        }
      })
    }
    
    // Mark absent students explicitly (optional, since default is false)
    if (record.absentees && Array.isArray(record.absentees) && record.absentees.length > 0) {
      record.absentees.forEach(pin => {
        // Absent is already false by default, so no need to set
        // But we can log for debugging if needed
        if (!registerData[dateStr][pin]) {
          console.log(`Student ${pin} not found in student list for date ${dateStr}`)
        }
      })
    }
  })

  return {
    weekStart: monday.toISOString().slice(0, 10),
    weekEnd: saturday.toISOString().slice(0, 10),
    weekDates,
    registerData,
    students: students
      .filter((student, index, arr) => arr.findIndex(s => s.pin === student.pin) === index) // Remove duplicates
      .sort((a, b) => a.pin.localeCompare(b.pin)) // Sort by full PIN
      .map(s => ({ pin: s.pin, name: s.name }))
  }
}

export async function getWeeklyRegister(req, res) {
  try {
    const { department, semester, shift, weekStart } = req.query || {}
    console.log('Weekly register request params:', { department, semester, shift, weekStart })
    
    if (!department || !semester || !shift || !weekStart) {
      return res
        .status(400)
        .json({ message: 'department, semester, shift, weekStart are required' })
    }

    const weeklyData = await getWeeklyRegisterData({ department, semester, shift, weekStart })
    
    console.log('Found students:', weeklyData.students.length)
    console.log('Found attendance records:', Object.keys(weeklyData.registerData).length * weeklyData.students.length * 7)

    return res.json(weeklyData)
  } catch (err) {
    console.error('Weekly register error:', err)
    const status = err.status || 500
    return res.status(status).json({ message: err.message || 'Failed to generate weekly register' })
  }
}

export async function exportWeeklyExcel(req, res) {
  try {
    const { department, semester, shift, weekStart } = req.query || {}
    if (!department || !semester || !shift || !weekStart) {
      return res
        .status(400)
        .json({ message: 'department, semester, shift, weekStart are required' })
    }

    // Get the same data as weekly register
    const weeklyData = await getWeeklyRegisterData({ department, semester, shift, weekStart })
    
    // Create workbook and worksheet
    const wb = XLSX.utils.book_new()
    const wsData = []
    
    // First row: Date headers (merged across 7 columns each)
    const firstRow = ['PIN', 'Name']
    weeklyData.weekDates.forEach(date => {
      // Add date in first cell, then empty cells for merging
      firstRow.push(`${date.formatted} ${date.day}`)
      for (let i = 0; i < 6; i++) { // Add 6 more empty cells for total of 7
        firstRow.push('')
      }
    })
    wsData.push(firstRow)
    
    // Second row: Period headers (P1-P7 for each day)
    const secondRow = ['', '']
    weeklyData.weekDates.forEach(date => {
      for (let period = 1; period <= 7; period++) {
        secondRow.push(`P${period}`)
      }
    })
    wsData.push(secondRow)
    
    // Add student data
    weeklyData.students.forEach(student => {
      const row = [student.pin, student.name]
      
      weeklyData.weekDates.forEach(date => {
        const dateStr = date.date
        for (let period = 1; period <= 7; period++) {
          const periodIndex = period - 1
          const isPresent = weeklyData.registerData[dateStr]?.[student.pin]?.[periodIndex]
          row.push(isPresent ? 'P' : 'A')
        }
      })
      
      wsData.push(row)
    })
    
    // Add summary information
    wsData.push([])
    wsData.push(['Week:', `${weeklyData.weekStart} to ${weeklyData.weekEnd}`])
    wsData.push(['Generated By:', 'Faculty Log Book System'])
    
    const ws = XLSX.utils.aoa_to_sheet(wsData)
    
    // Set column widths
    const colWidths = [
      { wch: 15 }, // PIN
      { wch: 25 }, // Name
    ]
    
    // Add auto-sized widths for each day (7 periods per day)
    weeklyData.weekDates.forEach(() => {
      for (let i = 0; i < 7; i++) {
        colWidths.push({ wch: 6 }) // Auto-sized period columns
      }
    })
    
    ws['!cols'] = colWidths
    
    // Center alignment for date headers and period headers
    const range = XLSX.utils.decode_range(ws['!ref'])
    
    // Center align date headers (row 0) - check each cell
    for (let C = 2; C <= range.e.c; C++) {
      const cellAddr = XLSX.utils.encode_cell({ r: 0, c: C })
      const cell = ws[cellAddr]
      if (cell && cell.v) { // Only apply to cells with values
        cell.s = {
          alignment: { horizontal: 'center', vertical: 'center' },
          font: { bold: true }
        }
      }
    }
    
    // Center align period headers (row 1)
    for (let C = 2; C <= range.e.c; C++) {
      const cellAddr = XLSX.utils.encode_cell({ r: 1, c: C })
      const cell = ws[cellAddr]
      if (cell) {
        cell.s = {
          alignment: { horizontal: 'center', vertical: 'center' },
          font: { bold: true }
        }
      }
    }
    
    // Add red color for absent students in data rows
    let startRow = 2 // Start from row 2 (after headers)
    weeklyData.students.forEach((student, studentIndex) => {
      const currentRow = startRow + studentIndex + 1
      let colIndex = 2 // Start after PIN and Name columns
      
      weeklyData.weekDates.forEach(date => {
        for (let period = 1; period <= 7; period++) {
          const cellAddr = XLSX.utils.encode_cell({ r: currentRow, c: colIndex })
          const cell = ws[cellAddr]
          if (cell && cell.v === 'A') {
            cell.s = {
              alignment: { horizontal: 'center', vertical: 'center' },
              fill: { fgColor: { rgb: "FFFFCCCC" }, patternType: "solid" },
              font: { color: { rgb: "FF000000" }, bold: true }
            }
          } else if (cell && cell.v === 'P') {
            cell.s = {
              alignment: { horizontal: 'center', vertical: 'center' },
              fill: { fgColor: { rgb: "FFCCFFCC" }, patternType: "solid" },
              font: { color: { rgb: "FF006600" }, bold: true }
            }
          }
          colIndex++
        }
      })
    })
    
    // Center align PIN and Name headers
    ws['A1'].s = { alignment: { horizontal: 'center', vertical: 'center' }, font: { bold: true } }
    ws['B1'].s = { alignment: { horizontal: 'center', vertical: 'center' }, font: { bold: true } }
    
    // Merge cells for date headers (merge 7 columns per day)
    let colIndex = 2 // Start after PIN and Name columns
    weeklyData.weekDates.forEach(date => {
      // Merge 7 columns for each day (rows 0-0, columns colIndex to colIndex+6)
      if (!ws['!merges']) ws['!merges'] = []
      ws['!merges'].push({ s: { r: 0, c: colIndex }, e: { r: 0, c: colIndex + 6 } })
      colIndex += 7
    })
    
    XLSX.utils.book_append_sheet(wb, ws, `Weekly Register - ${weekStart}`)

    const filename = `weekly_register_${weekStart}.xlsx`
    const excelBuffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)

    res.send(excelBuffer)
  } catch (err) {
    console.error('Weekly Excel export error:', err)
    const status = err.status || 500
    return res.status(status).json({ message: err.message || 'Failed to export weekly register' })
  }
}
